// Mocks generated by Mockito 5.4.5 from annotations
// in absmartly_sdk/test/client_config_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:absmartly_sdk/context_data_deserializer.dart' as _i2;
import 'package:absmartly_sdk/context_event_serializer.dart' as _i4;
import 'package:absmartly_sdk/json/context_data.dart' as _i3;
import 'package:absmartly_sdk/json/publish_event.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ContextDataDeserializer].
///
/// See the documentation for Mockito's code generation for more information.
class MockContextDataDeserializer extends _i1.Mock
    implements _i2.ContextDataDeserializer {
  @override
  _i3.ContextData? deserialize(List<int>? bytes, int? offset, int? length) =>
      (super.noSuchMethod(
            Invocation.method(#deserialize, [bytes, offset, length]),
            returnValueForMissingStub: null,
          )
          as _i3.ContextData?);
}

/// A class which mocks [ContextEventSerializer].
///
/// See the documentation for Mockito's code generation for more information.
class MockContextEventSerializer extends _i1.Mock
    implements _i4.ContextEventSerializer {
  @override
  List<int>? serialize(_i5.PublishEvent? publishEvent) =>
      (super.noSuchMethod(
            Invocation.method(#serialize, [publishEvent]),
            returnValueForMissingStub: null,
          )
          as List<int>?);
}
